name: Deploy FE to VPS via SSH

on:
  push:
    paths:
      - "src/my-porto/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker image
        working-directory: ./src/my-porto
        run: |
          docker build -t fuadgrimaldi/porto-frontend:latest .
          docker push fuadgrimaldi/porto-frontend:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "üîÅ Ganti ke direktori project..."
            cd ~/httpdocs/personal-app

            echo "üõë Stop container FE..."
            sudo docker-compose stop fe || true
            sudo docker-compose rm -f fe || true

            echo "üßº Hapus image lama..."
            sudo docker rmi fuadgrimaldi/porto-frontend:latest

            echo "üì• Pull image terbaru dari Docker Hub..."
            sudo docker pull fuadgrimaldi/porto-frontend:latest

            echo "üöÄ Jalankan container FE..."
            sudo docker-compose up -d fe

            echo "‚úÖ Reload nginx..."
            sudo nginx -t && sudo systemctl reload nginx
