name: Deploy FE to VPS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker image
        working-directory: ./src/my-porto
        run: |
          docker build -t fuadgrimaldi/porto-frontend:latest .
          docker push fuadgrimaldi/porto-frontend:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "ğŸ” Ganti ke direktori project..."
            cd ~/personal-app

            echo "ğŸ›‘ Stop container FE..."
            sudo docker-compose stop fe || true
            sudo docker-compose rm -f fe || true

            echo "ğŸ§¼ Hapus image lama..."
            sudo docker rmi fuadgrimaldi/porto-frontend:latest

            echo "ğŸ“¥ Pull image terbaru dari Docker Hub..."
            sudo docker pull fuadgrimaldi/porto-frontend:latest

            echo "ğŸš€ Jalankan container FE..."
            sudo docker-compose up -d fe

            echo "âœ… Reload nginx..."
            sudo nginx -t && sudo systemctl reload nginx
